[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:webserver]
command = /usr/sbin/nginx
autostart=true
autorestart=unexpected
exitcodes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
daemon=off
priority=10

[program:gunicorn]
command = /emerald_heart/bin/gunicorn -c /emerald_heart/gunicorn.conf.py emerald_heart.wsgi
autostart=true
autorestart=unexpected
stopsignal=INT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
directory=/emerald_heart/
priority=0

[program:migrations]
command = bash -c "/emerald_heart/bin/migrate.sh"
startsecs = 0
exitcodes = 0,1,2
autorestart = false
priority = 30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
