from __future__ import annotations

import re

IGNORECASE = re.I
"""Stash the re.I value."""

re_compile = re.compile
"""Stash the re.compile value."""


DISALLOWED_USER_AGENTS = [
    re_compile(r".+?“trendictionbot”.*", IGNORECASE),
    re_compile(r".+?adscanner.*", IGNORECASE),
    re_compile(r".+?ahrefsbot.*", IGNORECASE),
    re_compile(r".+?aspiegelbot.*", IGNORECASE),
    re_compile(r".+?awariosmartbot.*", IGNORECASE),
    re_compile(r".+?barkrowler.*", IGNORECASE),
    re_compile(r".+?blexbot.*", IGNORECASE),
    re_compile(r".+?bomborabot.*", IGNORECASE),
    re_compile(r".+?bubing.*", IGNORECASE),
    re_compile(r".+?bvbot.*", IGNORECASE),
    re_compile(r".+?checkmarknetwork.*", IGNORECASE),
    re_compile(r".+?cincraw.*", IGNORECASE),
    re_compile(r".+?clickagy.*", IGNORECASE),
    re_compile(r".+?cocolyzebot.*", IGNORECASE),
    re_compile(r".+?crawler@alexa.*", IGNORECASE),
    re_compile(r".+?developers[.]google[.]com/[+]/web/snippet.*", IGNORECASE),
    re_compile(r".+?df bot 1.0.*", IGNORECASE),
    re_compile(r".+?domaincrawler.*", IGNORECASE),
    re_compile(r".+?domainstatsbot.*", IGNORECASE),
    re_compile(r".+?domcopbot.*", IGNORECASE),
    re_compile(r".+?dotbot.*", IGNORECASE),
    re_compile(r".+?exabot-thumbnails.*", IGNORECASE),
    re_compile(r".+?exabot/3.0.*", IGNORECASE),
    re_compile(r".+?facebookexternalhit.*", IGNORECASE),
    re_compile(r".+?googleimageproxy.*", IGNORECASE),
    re_compile(r".+?grapeshotcrawler.*", IGNORECASE),
    re_compile(r".+?httrack.*", IGNORECASE),
    re_compile(r".+?ia_archiver.*", IGNORECASE),
    re_compile(r".+?internet-structure-research-project-bot.*", IGNORECASE),
    re_compile(r".+?jobboersebot.*", IGNORECASE),
    re_compile(r".+?linguee.*", IGNORECASE),
    re_compile(r".+?linkfluence.*", IGNORECASE),
    re_compile(r".+?magpie-crawler.*", IGNORECASE),
    re_compile(r".+?mail[.]ru_bot.*", IGNORECASE),
    re_compile(r".+?mediatoolkitbot.*", IGNORECASE),
    re_compile(r".+?megaindex.*", IGNORECASE),
    re_compile(r".+?megaindex.ru.*", IGNORECASE),
    re_compile(r".+?mj11bot.*", IGNORECASE),
    re_compile(r".+?mj12bot.*", IGNORECASE),
    re_compile(r".+?mj13bot.*", IGNORECASE),
    re_compile(r".+?mj14bot.*", IGNORECASE),
    re_compile(r".+?mj15bot.*", IGNORECASE),
    re_compile(r".+?nimbostratus.*", IGNORECASE),
    re_compile(r".+?omgili.*", IGNORECASE),
    re_compile(r".+?onalyticabot.*", IGNORECASE),
    re_compile(r".+?petalbot.*", IGNORECASE),
    re_compile(r".+?pubmatic crawler bot.*", IGNORECASE),
    re_compile(r".+?qwantify.*", IGNORECASE),
    re_compile(r".+?riddler.*", IGNORECASE),
    re_compile(r".+?rogerbot.*", IGNORECASE),
    re_compile(r".+?sbl-bot.*", IGNORECASE),
    re_compile(r".+?seekport.*", IGNORECASE),
    re_compile(r".+?semanticbot.*", IGNORECASE),
    re_compile(r".+?semrushbot.*", IGNORECASE),
    re_compile(r".+?seokicks-robot.*", IGNORECASE),
    re_compile(r".+?seoscanners[.]net.*", IGNORECASE),
    re_compile(r".+?serpstatbot.*", IGNORECASE),
    re_compile(r".+?seznambot/3.2.*", IGNORECASE),
    re_compile(r".+?sistrix.*", IGNORECASE),
    re_compile(r".+?sogou.*", IGNORECASE),
    re_compile(r".+?sqlmap.*", IGNORECASE),
    re_compile(r".+?traackr.*", IGNORECASE),
    re_compile(r".+?voilabot.*", IGNORECASE),
    re_compile(r".+?webtechbot.*", IGNORECASE),
    re_compile(r".+?whatcms”.*", IGNORECASE),
]
